### PR TITLE
Replace use of query-string dependency for URLSearchParams #571

### LINKED ISSUE #571: Replace use of `query-string` dependency for `URLSearchParams`
Upgrading to `query-string` v8+ has been [a pain point for codebases](https://github.com/sindresorhus/query-string/issues/366), and Learner Dashboard is no exception. 

What I've discovered is that our use for `query-string` in Learner Dashboard can be fulfilled with [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), which occurs in two files ([hook.js](https://github.com/openedx/frontend-app-learner-dashboard/blob/b5e2a9448077cd17e0c7f0af37cfdd40aeda0f50/src/containers/CoursesPanel/hooks.js#L4) and [src/data/services/lms/utils.js](https://github.com/openedx/frontend-app-learner-dashboard/blob/b5e2a9448077cd17e0c7f0af37cfdd40aeda0f50/src/data/services/lms/utils.js#L4)), and so instead of trying to fix the failed tests for upgrading `query-string` to v9, I suggest replacing it completely. 

This will require updating the tests for both files and removing the `query-string` dependency from `package.json`.

### PR DESCRIPTION
**Pull request by diana-villalvazo-wgu**
#### Description
We removed the use of `query-string` and replace the use of `stringify` and `stringifyUrl` for our own functions using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), fixed the related tests and deprecate the package.

#### Supporting information
This PR fixes #571 

#### How Has This Been Tested?
The creation of the url in the image (when you hit learner-dashboard) was built using this functions, it removes `user=undefined` from url params so we can get the proper response
Screenshot 2025-05-07 at 11 45 27 a m

### CODE REVIEW

**Review by vmnavarro94 — APPROVED** [review]
Nice job Diana, this looks good to me. 🚀

**Review by jacobo-dominguez-wgu — APPROVED** [review]

**Comment by arbrandes** [comment]
Thanks for this, @diana-villalvazo-wgu!  I'm going to do a proper review today or tomorrow.

File: src/containers/CoursesPanel/hooks.js [hunk 1]
```diff
@@ -27,12 +25,13 @@ export const useCourseListData = () => {
...
 
-  const querySearch = queryString.parse(window.location.search, { parseNumbers: true });
+  const querySearch = new URLSearchParams(window.location.search);
+  const disablePagination = querySearch.get('disable_pagination');
 
   const { numPages, visibleList } = reduxHooks.useCurrentCourseList({
     sortBy,
     filters,
-    pageSize: querySearch?.disable_pagination === 1 ? 0 : ListPageSize,
+    pageSize: disablePagination === 1 ? 0 : ListPageSize,
```
Comment (arbrandes) [inline src/containers/CoursesPanel/hooks.js:34]: `URLSearchParams.get()` returns a string or null ([reference](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get)).  Therefore, this strict comparison (`===`) is technically supposed to fail, because the string '1' should never strictly equal the number 1.  We should probably coerce `disablePagination` to be a number manually.

File: src/containers/CoursesPanel/hooks.test.js [hunk 2]
```diff
@@ -67,7 +67,7 @@ describe('CourseList hooks', () => {
       it('loads current course list with page size 0 if/when there is query param disable_pagination=1', () => {
         state.mock();
         state.mockVal(state.keys.sortBy, testSortBy);
-        queryString.parse.mockReturnValueOnce({ disable_pagination: 1 });
+        mockGet.mockReturnValueOnce(1);
```
Comment (arbrandes) [inline src/containers/CoursesPanel/hooks.test.js:70]: This test should be modified to return `'1'`, as opposed to `1`.

File: src/data/services/lms/utils.js [hunk 3]
```diff
@@ -1,6 +1,34 @@
-import queryString from 'query-string';
 import { getAuthenticatedHttpClient } from '@edx/frontend-platform/auth';
 
+/**
+ * stringify(query, existingQuery)
+ * simple wrapper to convert an object to a query string
+ * @param {object} query - object to convert
+ * @param {string} existingQuery - existing query string
+ * @returns {string} - query string
+ */
```
Comment (arbrandes) [inline src/data/services/lms/utils.js:9]: Thank you for the jsdoc!  Even if we're likely to soon move to Typescript, having the documentation will make that migration that much easier.  👍🏼

**Review by arbrandes — CHANGES_REQUESTED** [review]
Thanks again for doing this!  Nothing better than getting rid of deprecated libraries. 👍🏼 

I did suggest a couple of changes, however.  See the review comments.

File: src/containers/CoursesPanel/hooks.js (hunk 1 above)
Comment (dianavillalvazo) [reply src/containers/CoursesPanel/hooks.js:34]: you are right! will change this, thanks!

Comment (diana-villalvazo-wgu) [reply src/containers/CoursesPanel/hooks.js:34]: You are right! Will change it thanks!

Comment (diana-villalvazo-wgu) [reply src/containers/CoursesPanel/hooks.js]: Done!

File: src/containers/CoursesPanel/hooks.test.js (hunk 2 above)
Comment (diana-villalvazo-wgu) [reply src/containers/CoursesPanel/hooks.test.js]: Done!

**Review by arbrandes — APPROVED** [review]
I tested this in a dev environment and it works fine.  The code looks good, as well.  Thanks again!
